### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by RobertSpir** [xmatakt/bakalarka#2]
v linuxe mi to prekvapivo ide, ked som upravil tie cesty k shaderom
len ten control je roztiahnuty cez cele okno a z neznamych pricin sa tam pocas otvarania suboru spusta form_closing event.

**Comment by xmatakt** [comment]
Od kedy som to naposledy skusal som to uz neskusal v linuxe, viem ze tam bol problem s cestou k suboru, mozno windowsacke line endy, ale po odstraneni oboch problemov (druhy asi nebol) mi to aj tak neslo, mozno bude problem v mojej grafike a ovladacoch ked to Vam ide.

**Comment by RobertSpir** [comment]
je to mozne, lebo ja som si u mna v linuxe medzicasom (kvoli jednemu inemu projektu) nastavil nech sa vzdy natvrdo pouziva nvidia miesto integrovanej. Ale to, ze na niektorych grafikach v linuxe to nejde, nebude nas problem...

**Comment by RobertSpir** [comment]
opravil som linux problemy tak, ze som ten glcontrol strcil dovnutra jedneho panela. zaroven to aj z neznamych pricin opravilo ten problem s vyvolavanim form_closing eventu. Tiez som tam doplnil nastavenie cesty tak, ze by to malo automaticky fungovat aj v lin aj vo win. (netestoval som, tretikrat sa mi do lin bootovat nechce....)
